//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomNomScratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCourse
    {
        public string Name { get; set; }
        public int Price { get; set; }
        public int MfID { get; set; }
    }
}
