//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomNomScratch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NomNomEntities2 : DbContext
    {
        public NomNomEntities2()
            : base("name=NomNomEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<Appetizer> Appetizers { get; set; }
        public virtual DbSet<Beverage> Beverages { get; set; }
        public virtual DbSet<Dessert> Desserts { get; set; }
        public virtual DbSet<MainCourse> MainCourses { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<RankList> RankLists { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<UserRegister> UserRegisters { get; set; }
        public virtual DbSet<VoucherList> VoucherLists { get; set; }
    }
}
