//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomNomScratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankList
    {
        public int UserID { get; set; }
        public int TotalOrder { get; set; }
        public string SpecialVoucher { get; set; }
        public string Assign { get; set; }
        public int Spend { get; set; }
    
        public virtual UserRegister UserRegister { get; set; }
    }
}
